require("jhkim.plugins-setup")
require("jhkim.core.options")
require("jhkim.core.keymaps")
require("jhkim.core.colorscheme")
require("jhkim.plugins.comment")
require("jhkim.plugins.nvim-tree")
require("jhkim.plugins.lualine")
require("jhkim.plugins.telescope")
require("jhkim.plugins.nvim-cmp")
require("jhkim.plugins.lsp.mason")
require("jhkim.plugins.lsp.lspsaga")
require("jhkim.plugins.lsp.lspconfig")
require("jhkim.plugins.lsp.null-ls")
require("jhkim.plugins.autopairs")
require("jhkim.plugins.treesitter")
require("jhkim.plugins.git")
require("jhkim.plugins.gitsigns")
require("jhkim.plugins.bufferline")
-- require("jhkim.plugins.which-key")
require("jhkim.plugins.blankline")
require("jhkim.plugins.colorize")
-- require("jhkim.plugins.tailwindcss")
